parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Selene\InventoryBundle\:
        resource: '../src/*'

    Selene\InventoryBundle\Controller\:
        resource: '../src/Controller/*'
        public: true
    Selene\InventoryBundle\Repository\:
        resource: '../src/Repository/*'
        # tags: ['doctrine.repository_service']
        public: true
